# Generated by Django 3.2.7 on 2021-09-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_ingre', models.CharField(max_length=200)),
                ('recipe_process', models.TextField()),
            ],
        ),
    ]
